# -*- coding: utf-8 -*-
"""GROUP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpIH63pirPIfAlAhNw92p383HSElAJAV
"""



# !pip install selenium
import selenium

from selenium import *
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
import time
import requests

class RouteEstimation:
    def __init__(self, origin_city, destination_city):
        self.origin_city = origin_city
        self.destination_city = destination_city
        self.osrm_url = "http://router.project-osrm.org/route/v1/driving"
        self.nominatim_url = "https://nominatim.openstreetmap.org/search"

    def geocode_city(self, city_name):
        """Convert city name to (longitude, latitude) using OSM Nominatim."""
        params = {
            "q": city_name,
            "format": "json",
            "limit": 1
        }
        headers = {"User-Agent": "RouteEstimationApp/1.0"}
        response = requests.get(self.nominatim_url, params=params, headers=headers, timeout=10)
        response.raise_for_status()
        data = response.json()
        if not data:
            raise ValueError(f"City not found: {city_name}")
        lat = float(data[0]["lat"])
        lon = float(data[0]["lon"])
        return lon, lat

    def get_route(self):
        """Get drive time and distance between two cities."""
        lon1, lat1 = self.geocode_city(self.origin_city)
        lon2, lat2 = self.geocode_city(self.destination_city)

        params = {"overview": "false", "alternatives": "false", "steps": "false"}
        url = f"{self.osrm_url}/{lon1},{lat1};{lon2},{lat2}"

        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        route = data["routes"][0]
        duration_hrs = round((route["duration"] / 3600),2)
        distance_mi = round((route["distance"] * 0.00062137), 2)

        return {
            "origin": self.origin_city,
            "destination": self.destination_city,
            "duration_hrs": duration_hrs,
            "distance_mi": distance_mi
        }

route = RouteEstimation("Miami", "Los Angeles")
route.get_route()